// AUTO-GENERATED by scripts/sync-theme.mjs. Do not edit by hand.
// Run `npm run sync-tokens` after changing tokens.css or the .text-style-* /
// .h-* / .size-* / .min-w-* … rules in index.css. Read by src/utils/cn.ts.

/** DS theme scales (tailwind-merge theme keys), from the same tokens as the @theme block. */
export const DS_TW_MERGE_THEME: Readonly<Record<"text" | "radius" | "spacing" | "shadow", readonly string[]>> = {
  "text": [
    "label",
    "body",
    "hero-body",
    "hero-button",
    "mono",
    "subheading",
    "code-digit",
    "heading",
    "title",
    "hero",
    "cta-standard",
    "cta-big"
  ],
  "radius": [
    "slider-inner",
    "tight",
    "mini",
    "normal",
    "soft",
    "outline-frame",
    "checkbox",
    "avatar",
    "avatar-sm",
    "calendar-day"
  ],
  "spacing": [
    "xxxs",
    "xxs",
    "xs",
    "sm",
    "rg",
    "md",
    "lg",
    "xl",
    "xxl",
    "xxxl",
    "toast-inset",
    "table-placeholder-y",
    "sticker-y"
  ],
  "shadow": [
    "button",
    "button-secondary",
    "button-hover",
    "button-active",
    "menu",
    "standard",
    "cta",
    "focus-prominent",
    "focus-primary",
    "press-prominent",
    "press-primary",
    "focus-danger"
  ]
};

/** Every `.text-style-<role>` class defined in index.css. */
export const DS_TEXT_STYLE_ROLES: readonly string[] = [
  "button",
  "body",
  "hero-body",
  "hero-button",
  "mono",
  "label",
  "title",
  "heading",
  "subheading",
  "hero",
  "cta"
];

/** Custom sizing utilities defined in index.css @layer utilities, by tailwind-merge class group. */
export const DS_SIZE_UTILITIES: Readonly<Record<"h" | "w" | "size" | "min-h" | "min-w" | "max-h" | "max-w", readonly string[]>> = {
  "h": [
    "button",
    "button-sm",
    "button-medium",
    "button-big",
    "menu-label",
    "text-trigger",
    "linear-progress",
    "button-micro",
    "slider-track"
  ],
  "w": [],
  "size": [
    "button",
    "button-sm",
    "checkbox",
    "code-digit",
    "checkbox-icon",
    "avatar",
    "avatar-sm",
    "shape-button",
    "button-micro"
  ],
  "min-h": [
    "button"
  ],
  "min-w": [
    "menu",
    "button"
  ],
  "max-h": [],
  "max-w": []
};
